apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scrappy-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - YOUR_DOMAIN
        - app.YOUR_DOMAIN
        - docs.YOUR_DOMAIN
      secretName: scrappy-tls
  rules:
    - host: YOUR_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing
                port:
                  number: 80
    - host: app.YOUR_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scrappy
                port:
                  number: 3000
    - host: docs.YOUR_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  number: 80
